<?php

namespace Billmate\BillmateCheckout\Model\Payment;

/**
 * Pay In Store payment method model
 */

class BillmatePayments extends \Magento\Payment\Model\Method\AbstractMethod {

    /**
     * @var string
     */
    protected $_code = 'billmate_checkout';

    /**
     * @var bool
     */
    protected $_isGateway                   = true;

    /**
     * @var bool
     */
    protected $_canCapture                  = true;

    /**
     * @var bool
     */
    protected $_canCapturePartial           = false;

    /**
     * @var bool
     */
    protected $_canRefund                   = true;

    /**
     * @var bool
     */
    protected $_canRefundInvoicePartial     = false;

    /**
     * @var bool
     */
    protected $_isOffline					= false;

    /**
     * @var \Billmate\BillmateCheckout\Helper\Data
     */
    protected $helper;

    /**
     * @var Billmate
     */
    protected $billmateProvider;

    /**
     * BillmatePayments constructor.
     *
     * @param \Magento\Framework\Model\Context                             $context
     * @param \Magento\Framework\Registry                                  $registry
     * @param \Magento\Framework\Api\ExtensionAttributesFactory            $extensionFactory
     * @param \Magento\Framework\Api\AttributeValueFactory                 $customAttributeFactory
     * @param \Magento\Payment\Helper\Data                                 $paymentData
     * @param \Magento\Framework\App\Config\ScopeConfigInterface           $scopeConfig
     * @param \Magento\Payment\Model\Method\Logger                         $logger
     * @param \Magento\Framework\Module\ModuleListInterface                $moduleList
     * @param \Magento\Framework\Stdlib\DateTime\TimezoneInterface         $localeDate
     * @param \Billmate\BillmateCheckout\Helper\Data                       $_helper
     * @param \Billmate\BillmateCheckout\Model\Api\Billmate                $billmateProvider
     * @param \Magento\Framework\Model\ResourceModel\AbstractResource|null $resource
     * @param \Magento\Framework\Data\Collection\AbstractDb|null           $resourceCollection
     * @param array                                                        $data
     */
    public function __construct(
        \Magento\Framework\Model\Context $context,
        \Magento\Framework\Registry $registry,
        \Magento\Framework\Api\ExtensionAttributesFactory $extensionFactory,
        \Magento\Framework\Api\AttributeValueFactory $customAttributeFactory,
        \Magento\Payment\Helper\Data $paymentData,
        \Magento\Framework\App\Config\ScopeConfigInterface $scopeConfig,
        \Magento\Payment\Model\Method\Logger $logger,
        \Magento\Framework\Module\ModuleListInterface $moduleList,
        \Magento\Framework\Stdlib\DateTime\TimezoneInterface $localeDate,
        \Billmate\BillmateCheckout\Helper\Data $_helper,
        \Billmate\BillmateCheckout\Model\Api\Billmate $billmateProvider,
        \Magento\Framework\Model\ResourceModel\AbstractResource $resource = null,
        \Magento\Framework\Data\Collection\AbstractDb $resourceCollection = null,
        array $data = []
    ) {
        $this->helper = $_helper;
        $this->billmateProvider = $billmateProvider;
        parent::__construct(
            $context,
            $registry,
            $extensionFactory,
            $customAttributeFactory,
            $paymentData,
            $scopeConfig,
            $logger,
            $resource,
            $resourceCollection,
            $data
        );
    }

    public function canRefund()
    {
        return true;
    }

    public function canCapture()
    {
        return true;
    }

    public function canVoid()
    {
        return true;
    }

    public function isOffline()
    {
        return false;
    }

    public function getTitle()
    {
        return parent::getTitle(); // TODO: Change the autogenerated stub
    }

    protected function getBillMateProvider()
    {
        return $this->billmateProvider;
    }


    /**
     * @param \Magento\Payment\Model\InfoInterface $payment
     * @param float                                $amount
     *
     * @throws \Magento\Framework\Exception\LocalizedException
     */
    public function capture(\Magento\Payment\Model\InfoInterface $payment, $amount)
    {
        $bm = $this->getBillMateProvider();
        $values = array();

        $order = $payment->getOrder();

        if (!empty($order->getData('billmate_invoice_id'))){
            $values["PaymentData"] = array(
                "number" => $order->getData('billmate_invoice_id')
            );
            $bm->activatePayment($values);
            $payment->setTransactionId($order->getData('billmate_invoice_id'));
            $payment->setParentTransactionId($payment->getTransactionId());
            $transaction = $payment->addTransaction(\Magento\Sales\Model\Order\Payment\Transaction::TYPE_AUTH, null, true, "");
            $transaction->setIsClosed(true);
        }
        else {
            throw new \Magento\Framework\Exception\LocalizedException(__('ID has not been recived from Billmate'));
        }
    }

    /**
     * @param \Magento\Payment\Model\InfoInterface $payment
     *
     * @throws \Magento\Framework\Exception\LocalizedException
     */
    public function void(\Magento\Payment\Model\InfoInterface $payment)
    {
        $bm = $this->getBillMateProvider();
        $values = array();

        $order = $payment->getOrder();
        if (!empty($order->getData('billmate_invoice_id'))) {
            $values["PaymentData"] = array(
                "number" => $order->getData('billmate_invoice_id')
            );
            $bm->cancelPayment($values);
        }
        else {
            throw new \Magento\Framework\Exception\LocalizedException(__('ID has not been recived from Billmate'));
        }
    }

    /**
     * @param \Magento\Payment\Model\InfoInterface $payment
     *
     * @throws \Magento\Framework\Exception\LocalizedException
     */
    public function cancel(\Magento\Payment\Model\InfoInterface $payment)
    {
        $bm = $this->getBillMateProvider();
        $values = array();

        $order = $payment->getOrder();
        if (!empty($order->getData('billmate_invoice_id'))){
            $values["PaymentData"] = array(
                "number" => $order->getData('billmate_invoice_id')
            );
            $bm->cancelPayment($values);
        }
        else {
            throw new \Magento\Framework\Exception\LocalizedException(__('ID has not been recived from Billmate'));
        }
    }

    /**
     * @param \Magento\Payment\Model\InfoInterface $payment
     * @param float                                $amount
     *
     * @throws \Magento\Framework\Exception\LocalizedException
     */
    public function refund(\Magento\Payment\Model\InfoInterface $payment, $amount)
    {
        $bm = $this->getBillMateProvider();
        $values = array();

        $order = $payment->getOrder();
        if (!empty($order->getData('billmate_invoice_id'))){
            $values["PaymentData"] = array(
                "number" => $order->getData('billmate_invoice_id'),
                "partcredit" => "false"
            );
            $bm->creditPayment($values);
        }
        else {
            throw new \Magento\Framework\Exception\LocalizedException(__('ID has not been recived from Billmate'));
        }
    }
}