<script>
  require(
    ['jquery', 'Billmate_BillmateCheckout/js/ajax'],
    function($, BillmateAjax) {
      var ajaxUrl = '<?php echo $block->getAjaxUrl(); ?>';
      BillmateAjax.call(ajaxUrl);
    }
  );
</script>
<?php 
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	$priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data');
	$totals = $this->getTotals();
	$prods = $this->getCartProducts();
	$methods = $this->getShippingMethods();
?>
<div id="billmate-cart">
	<h2> <?php echo __('Shopping Cart'); ?></h2>

    <table id="shopping-cart-table" class="cart items data table">
        <thead>
            <tr>
                <th class="col item" scope="col"><span><?php echo __('Product'); ?></span></th>
                <th class="col price" scope="col"><span>Pris</span></th>
                <th class="col qty" scope="col"><span><?php echo __('Quantity'); ?></span></th>
                <th class="col subtotal" scope="col"><span><?php echo __('Sum'); ?></span></th>
            </tr>
        </thead>
        <tbody class="cart item">
            <?php foreach ($prods as $prod): ?>
            <tr class="item-info">
                <td data-th="Item" class="col item">
                    <strong class="product-item-name">
                        <p><?php echo $prod['name']; ?></p>
                        <?php if ($this->showOptions()): ?>
                            <span>
                                <?php echo $prod['options'];?>
                            </span>
                        <?php endif; ?>
                    </strong>
                </td>

                <td class="col price" data-th="price">
                    <span class="price"><?php echo $priceHelper->currency($prod['price'], true, false); ?></span>
                </td>

                <td class="col qty" data-th="qty">
                    <?php echo $prod['qty']; ?>
                </td>

                <td class="col subtotal" data-th="subtotal">
                    <span class="cart-price">
                        <span class="price"><?php echo $priceHelper->currency(($prod['price']*$prod['qty']), true, false); ?></span>
                    </span>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>



	<table class="totals">
		<tr>
			<td class="name">
				<?php echo __('Shipping'); ?>
			</td>
			<td class="price">
				<?php echo $this->getShippingPrice() ?>
			</td>
		</tr>
		<?php if ($this->hasDiscount()): ?>
            <tr>
				<td class="name">
					<?php echo __('Discount'); ?>
				</td>
				<td class="price">
					<?php echo $this->getDiscount(); ?>
				</td>
			</tr>
        <?php endif; ?>
		<tr>
			<td class="name">
				<?php echo __('Tax'); ?>
			</td>
			<td class="price">
				<?php echo $this->getTax(); ?>
			</td>
		</tr>
        <tr>
			<td class="name">
				<?php echo __('Total'); ?>
			</td>
			<td class="price">
				<?php echo $this->getGrandTotal(); ?>
			</td>
		</tr>
	</table>


	<div class="billmate-checkout-discount">
		<form action="javascript:void(0);">
            <div class="fieldset coupon">
                <div class="field">
                    <h1><?php echo __('Discount Codes'); ?></h1>
                    <input type="text" name="code" id="code" class="input-text">
                </div>

                <div class="actions-toolbar">
                    <div class="primary">
                        <button id="codeButton" class="action apply primary" type="button" value="<?php echo __('Apply Discount'); ?>">
                            <span><?php echo __('Apply Discount'); ?></span>
                        </button>
                    </div>
                </div>
            </div>
		</form>
	</div>

	<script>
		document.getElementById("code").addEventListener("keyup", function(event) {
			event.preventDefault();
			if (event.keyCode == 13) {
				document.getElementById("codeButton").click();
			}
		});
	</script>
	<div class="billmate_shipping_methods">
		<h1>  <?php echo __('Shipping Methods'); ?> </h1>
		<form>
			<?php $first = true; ?>
			<?php foreach ($methods as $method): ?>
				<?php if (isset($_SESSION['shipping_code'])): ?>
					<?php if ($_SESSION['shipping_code'] == $method['code']): ?>
						<div class="ship_methods">
							<input type="radio" class="radio" id="<?php echo $method['code'] ?>" name="method" value="<?php echo $method['code']; ?>" checked> 
							<label for="<?php echo $method['code']; ?>" class="radio_lable" >
								<?php echo $method['title'] . " " . $priceHelper->currency($method['price'], true, false); ?>
							</label>
						</div>
					<?php else: ?>
						<div class="ship_methods">
							<input type="radio" class="radio" id="<?php echo $method['code'] ?>" name="method" value="<?php echo $method['code']; ?>"> 
							<label for="<?php echo $method['code']; ?>" class="radio_lable" >
								<?php echo $method['title'] . " " . $priceHelper->currency($method['price'], true, false); ?>
							</label>
						</div>
					<?php endif; ?>
				<?php else: ?>
					<?php if ($first): ?>
						<?php $first = false; ?>
						<div class="ship_methods">
							<input type="radio" class="radio" id="<?php echo $method['code'] ?>" name="method" value="<?php echo $method['code']; ?>" checked> 
							<label for="<?php echo $method['code']; ?>" class="radio_lable" >
								<?php echo $method['title'] . " " . $priceHelper->currency($method['price'], true, false); ?>
							</label>
						</div>
					<?php else: ?>
						<div class="ship_methods">
							<input type="radio" class="radio" id="<?php echo $method['code'] ?>" name="method" value="<?php echo $method['code']; ?>"> 
							<label for="<?php echo $method['code']; ?>" class="radio_lable" >
								<?php echo $method['title'] . " " . $priceHelper->currency($method['price'], true, false); ?>
							</label>
						</div>
					<?php endif; ?>
				<?php endif; ?>
			<?php endforeach; ?>
		</form>
	</div>
</div>