<?php
/**
 * Shopping cart content template
 *
 * @var $block \Billmate\BillmateCheckout\Block\Checkout
 */
?>

<?php
    $url = $block->getUrl();
    $billmateData = $this->getBillmateCheckoutData();
?>
<script>
	var UPDATE_ADDRESS_URL = "<?php echo $url . 'billmatecheckout/billmateajax/updateaddress'; ?>";
	var UPDATE_PAYMENT_METHOD_URL = "<?php echo $url . 'billmatecheckout/billmateajax/updatepaymentmethod'; ?>";
	var UPDATE_SHIPPING_METHOD_URL = "<?php echo $url . 'billmatecheckout/billmateajax/updateshippingmethod'; ?>";
	var CREATE_ORDER_URL = "<?php echo $url . 'billmatecheckout/billmateajax/createorder'; ?>";
	var UPDATE_TOTALS_URL = "<?php echo $url . 'billmatecheckout/billmateajax/updatetotals'; ?>";
	var UPDATE_DISCOUNT_URL = "<?php echo $url . 'billmatecheckout/billmateajax/setdiscount'; ?>";
	var SET_PAYMENTMETHOD_URL = "<?php echo $url . 'billmatecheckout/billmateajax/setpaymentmethod'; ?>";
	require(
		['jquery', 'Billmate_BillmateCheckout/js/checkout'],
		function($, billmateajax) {}
	);
</script>
<div id="billmate-checkout">
    <?php if(isset($billmateData['url'])): ?>
        <iframe id="checkout" src="<?= $billmateData['url'] ?> "
                scrolling="no"
                sandbox="allow-same-origin allow-scripts allow-modals allow-popups allow-forms allow-top-navigation">
        </iframe>
    <?php else: ?>
        <div class="message-warning warning message" data-ui-id="message-success">
            <?= $billmateData['message'] ?>
        </div>
    <?php endif;?>
</div>