<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$url = $storeManager->getStore()->getBaseUrl();
?>
<script>
	var UPDATE_ADDRESS_URL = "<?php echo $url . 'billmatecheckout/billmateajax/updateaddress'; ?>";
	var UPDATE_PAYMENT_METHOD_URL = "<?php echo $url . 'billmatecheckout/billmateajax/updatepaymentmethod'; ?>";
	var UPDATE_SHIPPING_METHOD_URL = "<?php echo $url . 'billmatecheckout/billmateajax/updateshippingmethod'; ?>";
	var CREATE_ORDER_URL = "<?php echo $url . 'billmatecheckout/billmateajax/createorder'; ?>";
	var UPDATE_TOTALS_URL = "<?php echo $url . 'billmatecheckout/billmateajax/updatetotals'; ?>";
	var UPDATE_DISCOUNT_URL = "<?php echo $url . 'billmatecheckout/billmateajax/setdiscount'; ?>";
	var SET_PAYMENTMETHOD_URL = "<?php echo $url . 'billmatecheckout/billmateajax/setpaymentmethod'; ?>";
	require(
		['jquery', 'Billmate_BillmateCheckout/js/checkout'],
		function($, billmateajax) {}
	);
</script>
<div id="billmate-checkout">
<?php echo $this->getBillmateCheckout(); ?>
</div>